language: perl

perl: "5.18"

branches:
  only:
    - master

before_install:
    - cpanm --force Test::Unit::Debug
    - cpanm --quiet Parallel::ForkManager
    - cpanm --quiet IO::CaptureOutput
    - cpanm --quiet Time::HiRes
    - cpanm --quiet Date::Calc
